### ISSUE TITLE
Getting list of matching groups

### ISSUE THREAD

**Issue by lanwen** [VerbalExpressions/JavaVerbalExpressions#28]
Now `getText(str, 1)` returns concatenation of all groups that was found. Need ability to return it as `List<String>`

**Comment by redwerk** [comment]
Hi @lanwen ,  i am interested in the implementation of this feature and i could do the pull request if you have no developments on this issue.

Thanks!

**Comment by lanwen** [comment]
@redwerk Your help is welcome! I didn't do anything in this direction
