### ISSUE TITLE
lineBreak() has a capturing group

### ISSUE THREAD

**Issue by masih** [VerbalExpressions/JavaVerbalExpressions#48]
Hello,
The method [`lineBreak()`](https://github.com/VerbalExpressions/JavaVerbalExpressions/blob/master/src/main/java/ru/lanwen/verbalregex/VerbalExpression.java#L236) contains a capturing group, which results in shifting of group numbers; the following test fails:

```java
    final VerbalExpression expression = VerbalExpression.regex().
                        lineBreak()
                       .capture().find("some").endCapture().then(" text")
                       .build();
        assertEquals("some", expression.getText("\nsome text", 1));
```

Cheers

**Comment by lanwen** [comment]
Thanks for this bug! It will be very helpful of you send PR with the fix and this test for it
