### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by clankill3r** [VerbalExpressions/JavaVerbalExpressions#56]
Why not just release a binary (a .jar file).
I got it all working with maven, but it's such a pain in the ass.

**Comment by clankill3r** [comment]
Great project btw, sry I need to cool off. Been installing dependencies all day...

**Comment by lanwen** [comment]
You can always download jar from central:
http://repo1.maven.org/maven2/ru/lanwen/verbalregex/java-verbal-expressions/1.4/java-verbal-expressions-1.4.jar
